/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.42).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.DTO.*;
import io.swagger.model.User;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.security.Principal;
import java.util.List;
import java.util.UUID;

@Validated
@RequestMapping("/users")
@SecurityRequirement(name = "JWTAuth")
public interface UsersApi {

    @PostMapping
    ResponseEntity<User> createUser(@Valid @RequestBody CreateUserDTO createUserDTO);

    @GetMapping
    ResponseEntity<List<GetUserDTO>> getUsers(
            @Valid @RequestParam(value = "limit", defaultValue = "10") Integer limit,
            @Valid @RequestParam(value = "offset", defaultValue = "0") Integer offset,
            @Valid @RequestParam(value = "searchstrings", required = false) String searchStrings,
            @Valid @RequestParam(value = "Email", required = false) String Email
    );

    @GetMapping("/{userID}")
    ResponseEntity<GetUserDTO> getUserById(
            @Valid @PathVariable("userID") UUID userID,
            Principal principal
    );
    @PutMapping("/{userID}")
    ResponseEntity<GetUserDTO> updateUser(
            @Valid @PathVariable("userID") UUID userID,
            @Valid @RequestBody UpdateUserDTO updateUserDTO,
            Principal principal
    );

}

